baseURL = 'https://lambda.lv/'
title = 'Î»'
theme = "hugotex"
languageCode = 'en-us'
DefaultContentLanguage = "en"

paginate = 3
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

[author]
    name = "Luis Victoria"
    abstract = "Alpha Logica"

[taxonomies]
    category = "categories"
    tag = "tags"
    series = "series"
